version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8080"
    volumes:
      - shared-stuff:/stuff
    environment:
      PORT: 8080

  db:
    build: .
    ports:
      - "6500:8080"
    environment:
      ROOT_PWD: password
    volumes:
      - shared-stuff:/stuff
    

volumes:
  shared-stuff: